name: Unit, Component and Integration Tests
description: Run unit, component and integration tests
runs:
  using: 'composite'
  steps:
    - name: Restore Dependencies
      run: dotnet restore src/ora2pg-migration-audit.sln
      shell: sh

    - name: Restore Tools
      working-directory: src
      run: dotnet tool restore
      shell: sh

    - name: Build
      run: dotnet build src/ora2pg-migration-audit.sln --no-restore --configuration Release --verbosity minimal
      shell: sh

