name: Unit, Component and Integration Tests
description: Run unit, component and integration tests
runs:
  using: 'composite'
  steps:
    - name: Restore Dependencies
      run: dotnet restore src/ora2pg-migration-audit.sln
      shell: sh

    - name: Restore Tools
      working-directory: src
      run: dotnet tool restore
      shell: sh

    - name: Build
      run: dotnet build src/ora2pg-migration-audit.sln --no-restore --configuration Release --verbosity minimal
      shell: sh

    - name: Test
      run: dotnet test src/ora2pg-migration-audit.sln --no-restore --verbosity normal --logger "junit;LogFileName=results.xml" --collect "XPlat Code Coverage"
      shell: sh
      continue-on-error: true

    - name: Merge code coverage
      working-directory: src
      run: |
        dotnet-coverage merge **/*.cobertura.xml --recursive --output coverage.xml --output-format cobertura
      shell: sh

    - name: Generate code coverage
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: "src/coverage.xml"
        format: markdown
        output: both

    - name: Publish code coverage
      run: |
        echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
        cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      shell: sh

