name: Unit, Component and Integration Tests
description: Run unit, component and integration tests
runs:
  using: 'composite'
  steps:
    - name: Restore Dependencies
      run: dotnet restore src/ora2pg-migration-audit.sln
      shell: sh

    - name: Build
      run: dotnet build src/ora2pg-migration-audit.sln --no-restore --configuration Release --verbosity minimal
      shell: sh

    - name: Test
      run: dotnet test src/ora2pg-migration-audit.sln --no-restore --verbosity normal --logger "junit;LogFileName=results.xml" --collect "XPlat Code Coverage"
      shell: sh
      continue-on-error: true

    - name: Publish test reports
      working-directory: src
      run: |
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        
        # Find and parse all results.xml files
        for result_file in $(find . -name "results.xml"); do
          if [ -f "$result_file" ]; then
            # Extract test statistics from JUnit XML
            total=$(grep -oP 'tests="\K[^"]+' "$result_file" | head -1)
            failures=$(grep -oP 'failures="\K[^"]+' "$result_file" | head -1)
            errors=$(grep -oP 'errors="\K[^"]+' "$result_file" | head -1)
            skipped=$(grep -oP 'skipped="\K[^"]+' "$result_file" | head -1)
            
            # Calculate passed tests
            passed=$((total - failures - errors - skipped))
            
            # Output formatted results
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Total Tests:** $total" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ **Passed:** $passed" >> $GITHUB_STEP_SUMMARY
            echo "- ❌ **Failed:** $((failures + errors))" >> $GITHUB_STEP_SUMMARY
            echo "- ⏭️ **Skipped:** $skipped" >> $GITHUB_STEP_SUMMARY
          fi
        done
      shell: sh

    - name: Generate code coverage
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: "src/coverage.xml"
        format: markdown
        output: both

    - name: Publish code coverage
      run: |
        echo "## Code Coverage" >> $GITHUB_STEP_SUMMARY
        cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      shell: sh

